-- Supabase Live Schema Dump
-- Auto-generated by MCP

CREATE TABLE audit_logs (
id BIGSERIAL NOT NULL,
moderator_id character varying NULL,
action_type character varying NOT NULL,
target_id character varying NULL,
details text NULL,
created_at timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE collected_cards (
id BIGSERIAL NOT NULL,
student_id character varying NULL,
staff_id character varying NULL,
collected_at timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE event_config (
key character varying NOT NULL,
title character varying NOT NULL,
event_time timestamp with time zone NOT NULL
);

CREATE TABLE gallery_photos (
id BIGSERIAL NOT NULL,
src text NOT NULL,
caption text NOT NULL,
likes integer NULL DEFAULT 0,
student_id character varying NULL,
author_name character varying NULL,
created_at timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE live_chats (
id uuid NOT NULL,
content text NOT NULL,
student_id text NOT NULL,
tab text NOT NULL DEFAULT 'hype'::text,
created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE post_comments (
id BIGSERIAL NOT NULL,
post_id bigint NOT NULL,
student_id character varying NOT NULL,
content text NOT NULL,
created_at timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE posts (
id BIGSERIAL NOT NULL,
content text NOT NULL,
likes integer NULL DEFAULT 0,
type character varying NOT NULL DEFAULT 'hype'::character varying,
is_anonymous boolean NULL DEFAULT false,
is_hidden boolean NULL DEFAULT false,
student_id character varying NULL,
tags TEXT[] NULL DEFAULT '{}'::text[],
created_at timestamp with time zone NULL DEFAULT now(),
liked_by TEXT[] NULL DEFAULT '{}'::text[],
image_url text NULL,
is_pinned boolean NULL DEFAULT false
);

CREATE TABLE system_config (
key character varying NOT NULL,
value boolean NOT NULL DEFAULT true,
text_value text NULL,
int_value integer NULL
);

CREATE TABLE user_sessions (
session_token uuid NOT NULL DEFAULT gen_random_uuid(),
student_id character varying NULL,
created_at timestamp with time zone NULL DEFAULT now(),
expires_at timestamp with time zone NOT NULL
);

CREATE TABLE user_vibe_status (
student_id character varying NOT NULL,
current_mission_id bigint NULL,
strike_count integer NULL DEFAULT 0,
lock_count integer NULL DEFAULT 0,
locked_until timestamp with time zone NULL
);

CREATE TABLE users (
student_id character varying NOT NULL,
instance_id uuid NULL,
id uuid NOT NULL,
pin_hash character varying NULL,
nickname character varying NULL,
aud character varying NULL,
role character varying NULL,
faculty character varying NULL,
major character varying NULL,
email character varying NULL,
ig character varying NULL,
encrypted_password character varying NULL,
email_confirmed_at timestamp with time zone NULL,
role character varying NULL DEFAULT 'student'::character varying,
avatar_color character varying NULL DEFAULT '#496268'::character varying,
invited_at timestamp with time zone NULL,
images TEXT[] NULL DEFAULT '{}'::text[],
confirmation_token character varying NULL,
tags TEXT[] NULL DEFAULT '{}'::text[],
confirmation_sent_at timestamp with time zone NULL,
recovery_token character varying NULL,
created_at timestamp with time zone NULL DEFAULT now(),
bio text NULL,
recovery_sent_at timestamp with time zone NULL,
profile_pic_url text NULL,
email_change_token_new character varying NULL,
photo_pool TEXT[] NULL DEFAULT '{}'::text[],
email_change character varying NULL,
baan_position character varying NULL,
email_change_sent_at timestamp with time zone NULL,
house_position character varying NULL,
last_sign_in_at timestamp with time zone NULL,
raw_app_meta_data jsonb NULL,
immich_asset_id text NULL,
has_accepted_tos boolean NULL DEFAULT false,
raw_user_meta_data jsonb NULL,
is_super_admin boolean NULL,
created_at timestamp with time zone NULL,
updated_at timestamp with time zone NULL,
phone text NULL DEFAULT NULL,
phone_confirmed_at timestamp with time zone NULL,
phone_change text NULL DEFAULT ''::character varying,
phone_change_token character varying NULL DEFAULT ''::character varying,
phone_change_sent_at timestamp with time zone NULL,
confirmed_at timestamp with time zone NULL,
email_change_token_current character varying NULL DEFAULT ''::character varying,
email_change_confirm_status smallint NULL DEFAULT 0,
banned_until timestamp with time zone NULL,
reauthentication_token character varying NULL DEFAULT ''::character varying,
reauthentication_sent_at timestamp with time zone NULL,
is_sso_user boolean NOT NULL DEFAULT false,
deleted_at timestamp with time zone NULL,
is_anonymous boolean NOT NULL DEFAULT false
);

CREATE TABLE vibe_missions (
id BIGSERIAL NOT NULL,
sequence_order integer NOT NULL,
target_role character varying NOT NULL,
required_count integer NOT NULL,
created_at timestamp with time zone NULL DEFAULT now()
);

ALTER TABLE users ADD PRIMARY KEY (student_id);
ALTER TABLE posts ADD PRIMARY KEY (id);
ALTER TABLE posts ADD FOREIGN KEY (student_id) REFERENCES users (student_id);
ALTER TABLE gallery_photos ADD PRIMARY KEY (id);
ALTER TABLE gallery_photos ADD FOREIGN KEY (student_id) REFERENCES users (student_id);
ALTER TABLE system_config ADD PRIMARY KEY (key);
ALTER TABLE post_comments ADD PRIMARY KEY (id);
ALTER TABLE post_comments ADD FOREIGN KEY (post_id) REFERENCES posts (id);
ALTER TABLE post_comments ADD FOREIGN KEY (student_id) REFERENCES users (student_id);
ALTER TABLE event_config ADD PRIMARY KEY (key);
ALTER TABLE vibe_missions ADD PRIMARY KEY (id);
ALTER TABLE user_vibe_status ADD PRIMARY KEY (student_id);
ALTER TABLE user_vibe_status ADD FOREIGN KEY (student_id) REFERENCES users (student_id);
ALTER TABLE user_vibe_status ADD FOREIGN KEY (current_mission_id) REFERENCES vibe_missions (id);
ALTER TABLE collected_cards ADD PRIMARY KEY (id);
ALTER TABLE collected_cards ADD FOREIGN KEY (student_id) REFERENCES users (student_id);
ALTER TABLE collected_cards ADD FOREIGN KEY (staff_id) REFERENCES users (student_id);
ALTER TABLE audit_logs ADD PRIMARY KEY (id);
ALTER TABLE audit_logs ADD FOREIGN KEY (moderator_id) REFERENCES users (student_id);
ALTER TABLE user_sessions ADD PRIMARY KEY (session_token);
ALTER TABLE user_sessions ADD FOREIGN KEY (student_id) REFERENCES users (student_id);
ALTER TABLE live_chats ADD PRIMARY KEY (id);
ALTER TABLE live_chats ADD FOREIGN KEY (student_id) REFERENCES users (student_id);


ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE collected_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_vibe_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE vibe_missions ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Allow all select" ON users FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all select" ON posts FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all select" ON post_comments FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow insert/update users" ON users FOR ALL TO PUBLIC USING (true);
CREATE POLICY "Allow insert posts" ON posts FOR INSERT TO PUBLIC WITH CHECK (true);
CREATE POLICY "Allow insert comments" ON post_comments FOR INSERT TO PUBLIC WITH CHECK (true);
CREATE POLICY "Allow select for all" ON event_config FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all for all" ON event_config FOR ALL TO PUBLIC USING (true);
CREATE POLICY "Allow all select vibe_missions" ON vibe_missions FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all vibe_missions" ON vibe_missions FOR ALL TO PUBLIC USING (true);
CREATE POLICY "Allow all select user_vibe_status" ON user_vibe_status FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all user_vibe_status" ON user_vibe_status FOR ALL TO PUBLIC USING (true);
CREATE POLICY "Allow all select collected_cards" ON collected_cards FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all collected_cards" ON collected_cards FOR ALL TO PUBLIC USING (true);
CREATE POLICY "Allow all select audit_logs" ON audit_logs FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow insert audit_logs" ON audit_logs FOR INSERT TO PUBLIC WITH CHECK (true);
CREATE POLICY "Allow all user_sessions" ON user_sessions FOR ALL TO PUBLIC USING (true);
CREATE POLICY "live_chats_select" ON live_chats FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "live_chats_insert" ON live_chats FOR INSERT TO PUBLIC WITH CHECK ((EXISTS ( SELECT 1
   FROM users
  WHERE ((users.student_id)::text = live_chats.student_id))));
CREATE POLICY "Allow all select" ON system_config FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all for system_config" ON system_config FOR ALL TO PUBLIC USING (true);


CREATE OR REPLACE FUNCTION public.delete_post_secure(p_post_id bigint, p_student_id character varying, p_pin_hash character varying)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_role varchar;
    v_post_author varchar;
BEGIN
    SELECT role INTO v_role FROM users WHERE student_id = p_student_id AND pin_hash = p_pin_hash;
    IF v_role IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: Invalid student ID or PIN';
    END IF;
    
    SELECT student_id INTO v_post_author FROM posts WHERE id = p_post_id;
    
    IF v_post_author = p_student_id OR v_role IN ('moderator', 'media_admin', 'staff') THEN
        DELETE FROM posts WHERE id = p_post_id;
        
        -- Insert into audit logs
        INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
        VALUES (
            CASE WHEN v_role IN ('moderator', 'media_admin', 'staff') THEN p_student_id ELSE NULL END,
            'post_delete',
            p_post_id::text,
            'Post deleted by ' || v_role || ' ' || p_student_id || ' (Author: ' || COALESCE(v_post_author, 'unknown') || ')'
        );
        
        RETURN true;
    ELSE
        RAISE EXCEPTION 'Unauthorized to delete this post';
    END IF;
END;
$function$



CREATE OR REPLACE FUNCTION public.swipe_card_secure(p_student_id character varying, p_staff_id character varying, p_direction character varying, p_pin_hash character varying)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_user_role VARCHAR;
    v_user_exists BOOLEAN;
    v_target_role VARCHAR;
    v_target_major VARCHAR;
    v_target_name VARCHAR;
    v_mission_id BIGINT;
    v_req_role VARCHAR;
    v_req_count INT;
    v_current_collected INT;
    v_strike_count INT;
    v_lock_count INT;
    v_locked_until TIMESTAMPTZ;
    v_max_strikes INT;
    v_base_cooldown INT;
    v_max_cooldown INT;
    v_cooldown INT;
    v_new_lock_until TIMESTAMPTZ;
    v_next_mission_id BIGINT;
BEGIN
    -- 1. Authentication Check
    SELECT role, EXISTS(SELECT 1 FROM users WHERE student_id = p_student_id) 
    INTO v_user_role, v_user_exists
    FROM users 
    WHERE student_id = p_student_id AND pin_hash = p_pin_hash;

    IF v_user_exists IS NOT TRUE THEN
        RETURN json_build_object('status', 'error', 'message', 'Unauthorized: Invalid credentials or un-registered account');
    END IF;

    -- 2. Lockout Check
    SELECT strike_count, lock_count, locked_until, current_mission_id
    INTO v_strike_count, v_lock_count, v_locked_until, v_mission_id
    FROM user_vibe_status
    WHERE student_id = p_student_id;

    -- Initialize user status if not present
    IF NOT FOUND THEN
        -- Get the first mission
        SELECT id INTO v_mission_id FROM vibe_missions ORDER BY sequence_order ASC LIMIT 1;
        
        INSERT INTO user_vibe_status (student_id, current_mission_id, strike_count, lock_count, locked_until)
        VALUES (p_student_id, v_mission_id, 0, 0, NULL);
        
        v_strike_count := 0;
        v_lock_count := 0;
        v_locked_until := NULL;
    END IF;

    IF v_locked_until IS NOT NULL AND v_locked_until > NOW() THEN
        RETURN json_build_object(
            'status', 'locked', 
            'locked_until', v_locked_until, 
            'seconds_remaining', EXTRACT(EPOCH FROM (v_locked_until - NOW()))
        );
    END IF;

    -- 3. Resolve Target Details
    SELECT role, major, nickname INTO v_target_role, v_target_major, v_target_name
    FROM users
    WHERE student_id = p_staff_id;

    IF NOT FOUND THEN
        RETURN json_build_object('status', 'error', 'message', 'Target user not found');
    END IF;

    -- Ensure we have an active mission
    IF v_mission_id IS NULL THEN
        -- Default to first mission
        SELECT id INTO v_mission_id FROM vibe_missions ORDER BY sequence_order ASC LIMIT 1;
        UPDATE user_vibe_status SET current_mission_id = v_mission_id WHERE student_id = p_student_id;
    END IF;

    -- Retrieve active mission spec
    SELECT target_role, required_count
    INTO v_req_role, v_req_count
    FROM vibe_missions
    WHERE id = v_mission_id;

    IF NOT FOUND THEN
        -- No active mission spec
        RETURN json_build_object('status', 'all_complete', 'message', 'All missions already completed!');
    END IF;

    -- Get penalty configurations from system_config
    SELECT int_value INTO v_max_strikes FROM system_config WHERE key = 'max_allowed_strikes';
    IF v_max_strikes IS NULL THEN v_max_strikes := 5; END IF;

    SELECT int_value INTO v_base_cooldown FROM system_config WHERE key = 'base_cooldown_minutes';
    IF v_base_cooldown IS NULL THEN v_base_cooldown := 1; END IF;

    SELECT int_value INTO v_max_cooldown FROM system_config WHERE key = 'max_cooldown_minutes';
    IF v_max_cooldown IS NULL THEN v_max_cooldown := 30; END IF;

    -- 4. Evaluate Swipe Logic
    IF p_direction = 'right' THEN
        IF v_target_major = v_req_role OR v_target_role = v_req_role THEN
            -- CORRECT COLLECT
            INSERT INTO collected_cards (student_id, staff_id)
            VALUES (p_student_id, p_staff_id)
            ON CONFLICT DO NOTHING;

            SELECT COUNT(*)::INT INTO v_current_collected
            FROM collected_cards cc
            JOIN users u ON cc.staff_id = u.student_id
            WHERE cc.student_id = p_student_id 
              AND (u.major = v_req_role OR u.role = v_req_role);

            IF v_current_collected >= v_req_count THEN
                SELECT id INTO v_next_mission_id 
                FROM vibe_missions 
                WHERE sequence_order > (SELECT sequence_order FROM vibe_missions WHERE id = v_mission_id)
                ORDER BY sequence_order ASC 
                LIMIT 1;

                UPDATE user_vibe_status 
                SET current_mission_id = v_next_mission_id,
                    strike_count = 0,
                    lock_count = 0,
                    locked_until = NULL
                WHERE student_id = p_student_id;

                RETURN json_build_object(
                    'status', 'mission_cleared',
                    'collected_staff_name', v_target_name,
                    'current_count', v_current_collected,
                    'required_count', v_req_count,
                    'next_mission_id', v_next_mission_id
                );
            ELSE
                RETURN json_build_object(
                    'status', 'collected',
                    'collected_staff_name', v_target_name,
                    'current_count', v_current_collected,
                    'required_count', v_req_count
                );
            END IF;
        ELSE
            -- INCORRECT COLLECT (Strike!)
            v_strike_count := v_strike_count + 1;
            IF v_strike_count >= v_max_strikes THEN
                v_cooldown := v_base_cooldown * power(2, v_lock_count);
                IF v_cooldown > v_max_cooldown THEN v_cooldown := v_max_cooldown; END IF;
                v_new_lock_until := NOW() + (v_cooldown * INTERVAL '1 minute');

                UPDATE user_vibe_status 
                SET strike_count = 0,
                    lock_count = lock_count + 1,
                    locked_until = v_new_lock_until
                WHERE student_id = p_student_id;

                -- Log system lockout
                INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
                VALUES (NULL, 'system_lockout', p_student_id, 'User locked out for ' || v_cooldown::text || ' minutes due to strike limit (incorrect collect on staff ID: ' || p_staff_id || ')');

                RETURN json_build_object(
                    'status', 'locked', 
                    'locked_until', v_new_lock_until, 
                    'cooldown_minutes', v_cooldown
                );
            ELSE
                UPDATE user_vibe_status 
                SET strike_count = v_strike_count
                WHERE student_id = p_student_id;

                -- Log system strike
                INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
                VALUES (NULL, 'system_strike', p_student_id, 'Strike issued to user (incorrect collect on staff ID: ' || p_staff_id || ') (Strike count: ' || v_strike_count::text || '/' || v_max_strikes::text || ')');

                RETURN json_build_object(
                    'status', 'strike',
                    'strike_count', v_strike_count,
                    'max_strikes', v_max_strikes
                );
            END IF;
        END IF;
    ELSE
        -- LEFT SWIPE (Skip)
        IF v_target_major = v_req_role OR v_target_role = v_req_role THEN
            -- MISSED OPPORTUNITY (Strike!)
            v_strike_count := v_strike_count + 1;
            IF v_strike_count >= v_max_strikes THEN
                v_cooldown := v_base_cooldown * power(2, v_lock_count);
                IF v_cooldown > v_max_cooldown THEN v_cooldown := v_max_cooldown; END IF;
                v_new_lock_until := NOW() + (v_cooldown * INTERVAL '1 minute');

                UPDATE user_vibe_status 
                SET strike_count = 0,
                    lock_count = lock_count + 1,
                    locked_until = v_new_lock_until
                WHERE student_id = p_student_id;

                -- Log system lockout
                INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
                VALUES (NULL, 'system_lockout', p_student_id, 'User locked out for ' || v_cooldown::text || ' minutes due to incorrect skip on staff ID: ' || p_staff_id);

                RETURN json_build_object(
                    'status', 'locked', 
                    'locked_until', v_new_lock_until, 
                    'cooldown_minutes', v_cooldown
                );
            ELSE
                UPDATE user_vibe_status 
                SET strike_count = v_strike_count
                WHERE student_id = p_student_id;

                -- Log system strike
                INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
                VALUES (NULL, 'system_strike', p_student_id, 'Strike issued to user due to incorrect skip on staff ID: ' || p_staff_id || ' (Strike count: ' || v_strike_count::text || '/' || v_max_strikes::text || ')');

                RETURN json_build_object(
                    'status', 'strike',
                    'strike_count', v_strike_count,
                    'max_strikes', v_max_strikes
                );
            END IF;
        ELSE
            RETURN json_build_object(
                'status', 'skipped'
            );
        END IF;
    END IF;
END;
$function$



CREATE OR REPLACE FUNCTION public.broadcast_emergency_message(p_session_token uuid, p_active boolean, p_text text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_student_id VARCHAR;
    v_role VARCHAR;
BEGIN
    -- Validate session token and check expiration
    SELECT s.student_id, u.role INTO v_student_id, v_role
    FROM user_sessions s
    JOIN users u ON s.student_id = u.student_id
    WHERE s.session_token = p_session_token AND s.expires_at > NOW();

    -- If no valid session is found, throw an exception
    IF v_student_id IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: Invalid or expired session token';
    END IF;

    -- Verify that the user has administrative privileges
    IF v_role IS NULL OR (v_role != 'moderator' AND v_role != 'media_admin') THEN
        RAISE EXCEPTION 'Unauthorized: Insufficient administrative privileges';
    END IF;

    -- Upsert the emergency configuration in system_config
    INSERT INTO system_config (key, value, text_value)
    VALUES ('emergency_announcement', p_active, p_text)
    ON CONFLICT (key) DO UPDATE
    SET value = p_active, text_value = p_text;

    -- Log the administrative action in audit logs
    INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
    VALUES (v_student_id, 'emergency_broadcast', 'system_config', 'Broadcast updated: active=' || p_active::text || ', text="' || p_text || '"');

    RETURN json_build_object('status', 'success', 'message', 'Broadcast saved successfully');
END;
$function$



CREATE OR REPLACE FUNCTION public.delete_comment_secure(p_comment_id bigint, p_student_id character varying, p_pin_hash character varying)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_role varchar;
    v_comment_author varchar;
BEGIN
    SELECT role INTO v_role FROM users WHERE student_id = p_student_id AND pin_hash = p_pin_hash;
    IF v_role IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: Invalid student ID or PIN';
    END IF;
    
    SELECT student_id INTO v_comment_author FROM post_comments WHERE id = p_comment_id;
    
    IF v_comment_author = p_student_id OR v_role IN ('moderator', 'media_admin', 'staff') THEN
        DELETE FROM post_comments WHERE id = p_comment_id;
        
        -- Insert into audit logs
        INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
        VALUES (
            CASE WHEN v_role IN ('moderator', 'media_admin', 'staff') THEN p_student_id ELSE NULL END,
            'comment_delete',
            p_comment_id::text,
            'Comment deleted by ' || v_role || ' ' || p_student_id || ' (Author: ' || COALESCE(v_comment_author, 'unknown') || ')'
        );
        
        RETURN true;
    ELSE
        RAISE EXCEPTION 'Unauthorized to delete this comment';
    END IF;
END;
$function$



CREATE OR REPLACE FUNCTION public.pin_post_secure(p_post_id bigint, p_student_id character varying, p_pin_hash character varying, p_is_pinned boolean)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_role varchar;
BEGIN
    SELECT role INTO v_role FROM users WHERE student_id = p_student_id AND pin_hash = p_pin_hash;
    IF v_role IS NULL THEN
        RAISE EXCEPTION 'Unauthorized: Invalid student ID or PIN';
    END IF;
    
    IF v_role IN ('moderator', 'media_admin', 'staff') THEN
        UPDATE posts SET is_pinned = p_is_pinned WHERE id = p_post_id;
        
        -- Insert into audit logs
        INSERT INTO audit_logs (moderator_id, action_type, target_id, details)
        VALUES (
            p_student_id,
            'post_pin',
            p_post_id::text,
            'Post pin status set to ' || p_is_pinned::text || ' by ' || v_role || ' ' || p_student_id
        );
        
        RETURN true;
    ELSE
        RAISE EXCEPTION 'Unauthorized to pin this post';
    END IF;
END;
$function$



CREATE OR REPLACE FUNCTION public.delete_chat_message_secure(p_message_id bigint, p_student_id text, p_pin_hash text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_role TEXT;
BEGIN
  SELECT role INTO v_role FROM public.users
    WHERE student_id = p_student_id AND pin_hash = p_pin_hash;
  IF v_role IS NULL OR v_role = 'student' THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  DELETE FROM public.live_chats WHERE id = p_message_id;
END;
$function$



CREATE OR REPLACE FUNCTION public.delete_chat_message_secure(p_message_id uuid, p_student_id text, p_pin_hash text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_role TEXT;
BEGIN
  SELECT role INTO v_role FROM public.users
    WHERE student_id = p_student_id AND pin_hash = p_pin_hash;
  IF v_role IS NULL OR v_role = 'student' THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  DELETE FROM public.live_chats WHERE id = p_message_id;
END;
$function$



-- Seeds extracted from original schema
INSERT INTO users (student_id, role, nickname, faculty, major, avatar_color) VALUES
('6688216', 'superadmin', 'Super Boss', 'Engineering', 'Computer Science', '#7c563f'),
('6688217', 'media_admin', 'Photo Lead', 'Fine Arts', 'Photography', '#496268'),
('6688218', 'staff', 'Staff Team', 'Arts', 'Event Management', '#9d806c'),
('6688219', 'student', NULL, NULL, NULL, '#a38c75'); -- Not yet registered profile

-- Seed a student with pre-hashed PIN: '123456'
-- SHA-256 hash of '123456' is '8d969ee76d243c509a8f3119717a286940004c4e15f226c70b8e4001b6579500'
INSERT INTO users (student_id, role, nickname, faculty, major, pin_hash, avatar_color) VALUES
('6688220', 'student', 'First Junior', 'Science', 'Physics', '8d969ee76d243c509a8f3119717a286940004c4e15f226c70b8e4001b6579500', '#5b6c6b');
-- Seed Vibe Check profiles (students who have completed profiles)
INSERT INTO users (student_id, role, nickname, faculty, major, pin_hash, avatar_color, images, photo_pool, tags, bio) VALUES
('6688221', 'student', 'Elena', 'Architecture', 'Architecture Major', 'dummy_hash', '#496268', 
  ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=700&fit=crop'],
  ARRAY[
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&h=700&fit=crop'
  ], 
  ARRAY['Coffee ☕', 'Night Owl 🦉', 'Adventures'],
  'Architect student who loves sketching buildings and exploring city life.'),

('6688222', 'student', 'Marcus', 'Engineering', 'Computer Science', 'dummy_hash', '#7c563f', 
  ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=700&fit=crop'],
  ARRAY[
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&h=700&fit=crop'
  ], 
  ARRAY['Music 🎸', 'Coding', 'Study Buddy'],
  'Developer who spends too much time on side projects and listening to classic rock.'),

('6688223', 'student', 'Sophia', 'Fine Arts', 'Visual Arts', 'dummy_hash', '#8c7b74', 
  ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&h=700&fit=crop'],
  ARRAY[
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&h=700&fit=crop'
  ], 
  ARRAY['Art 🎨', 'Sketching', 'Creative'],
  'Fine arts student specializing in watercolor and portrait drawings.'),

('6688224', 'student', 'Kai', 'Science', 'Environmental Science', 'dummy_hash', '#9d806c', 
  ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&h=700&fit=crop'],
  ARRAY[
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&h=700&fit=crop'
  ], 
  ARRAY['Nature 🌿', 'Hiking', 'Plants'],
  'Nature enthusiast, plant dad, and amateur photographer.'),

('6688225', 'staff', 'P'' Bell', 'Senior Staff', 'Senior Staff (Baan 7)', 'dummy_hash', '#a38c75', 
  ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&h=700&fit=crop'],
  ARRAY[
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&h=700&fit=crop',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=700&fit=crop'
  ], 
  ARRAY['Staff 🧡', 'Mentor', 'Orientation'],
  'Orientation staff ready to answer all your questions and show you the best spots!');
-- Seed Board Config toggles
INSERT INTO system_config (key, value) VALUES
('enable_hype_board', true),
('enable_memory_board', true),
('vibecheck_enabled', true);

INSERT INTO system_config (key, value, text_value, int_value) VALUES
('emergency_announcement', false, '', 0),
('max_allowed_strikes', true, NULL, 5),
('base_cooldown_minutes', true, NULL, 1),
('max_cooldown_minutes', true, NULL, 30);

INSERT INTO vibe_missions (sequence_order, target_role, required_count) VALUES
(1, 'โสต', 2),
(2, 'สันทนาการ', 3),
(3, 'พี่กลุ่ม', 4);
-- Seed Next Event config
INSERT INTO event_config (key, title, event_time) VALUES
('next_event', 'First Meet', NOW() + INTERVAL '1 day');
-- Seed Initial Board Posts
INSERT INTO posts (content, likes, type, is_anonymous, student_id, tags) VALUES
('Just finished the campus tour. The new science building looks amazing! Can''t wait for classes to start. 🔥', 24, 'hype', false, '6688222', ARRAY['#Ween2026']),
('Welcome incoming freshmen! Make sure to attend the opening ceremony tomorrow at 9 AM in the main hall. It''s going to be spectacular.', 102, 'hype', false, '6688225', ARRAY['#Hype']),
('Look at the beautiful sunrise over the clock tower! Excited to capture more orientation photos.', 15, 'memory', false, '6688217', ARRAY['#Memory']),
('Feeling super pumped to meet everyone! Shoutout to the organizers! 🚀', 8, 'hype', true, '6688220', ARRAY['#Ween2026']);
-- Seed Gallery Images
INSERT INTO gallery_photos (src, caption, likes, student_id, author_name) VALUES
('https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&h=400&fit=crop', 'First day squad!', 56, '6688221', 'Elena'),
('https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=600&h=400&fit=crop', 'Campus sunset 🌅', 89, '6688222', 'Marcus'),
('https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&h=400&fit=crop', 'Opening ceremony prep', 134, '6688225', 'P'' Bell'),
('https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600&h=400&fit=crop', 'Team building games', 72, '6688221', 'Elena'),
('https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop', 'Study group vibes', 45, '6688224', 'Kai'),
('https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&h=400&fit=crop', 'Tech workshop', 67, '6688222', 'Marcus'),
('https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?w=600&h=400&fit=crop', 'Game night mayhem 🎮', 98, '6688220', 'First Junior'),
('https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=400&fit=crop', 'Baan 7 forever!', 201, '6688223', 'Sophia');